Switch to bash regex for URL transformation

diff --git a/yt_podoff b/yt_podoff
--- a/yt_podoff
+++ b/yt_podoff
@@ -31,11 +31,15 @@ for F in "$@"; do
     FEED_URLS=(); while read U; do
 
       # ...and transform them into RSS feed URLs (ref: https://stackoverflow.com/a/31535120)
-      case "$U" in
-        */channel/*) FEED_URLS+=("https://www.youtube.com/feeds/videos.xml?channel_id=${U##*/}");;
-        */user/*) FEED_URLS+=("https://www.youtube.com/feeds/videos.xml?user=${U##*/}");;
-        */playlist?list=*) FEED_URLS+=("https://www.youtube.com/feeds/videos.xml?playlist_id=${U##*=}");;
-      esac
+      if [[ "$U" =~ .*youtube\.com/channel/([^/]+).* ]]; then
+        FEED_URLS+=("https://www.youtube.com/feeds/videos.xml?channel_id=${BASH_REMATCH[1]}")
+      elif [[ "$U" =~ .*youtube\.com/user/([^/]+).* ]]; then
+        FEED_URLS+=("https://www.youtube.com/feeds/videos.xml?user=${BASH_REMATCH[1]}")
+      elif [[ "$U" =~ .*youtube\.com.*list=([^&]+).* ]]; then
+        FEED_URLS+=("https://www.youtube.com/feeds/videos.xml?playlist_id=${BASH_REMATCH[1]}")
+      else
+        echo "ERROR: Unrecognized URL '$U', skipping." >&2
+      fi
 
     done <"$(basename "$F")"
 
